var plateIron = <gregtech:gt.metaitem.01:17032>;
var plateWroughtIron = <gregtech:gt.metaitem.01:17304>;
var plateAluminium = <gregtech:gt.metaitem.01:17019>;
var shutterModule = <gregtech:gt.metaitem.01:32749>;
recipes.addShaped(<gregtech:gt.metatool.01>.withTag({ench: [{lvl: 1 as short, id: 20 as short}], "GT.ToolStats": {PrimaryMaterial: "<minecraft:flint>", MaxDamage: 6400 as long, SecondaryMaterial: "Wood"}}), [[null, <minecraft:flint>, null],[null, <minecraft:flint>, null],[null, <ore:stickWood>, null]]);
recipes.addShaped(<gregtech:gt.metatool.01:2>.withTag({"GT.ToolStats": {PrimaryMaterial: "<minecraft:flint>", MaxDamage: 6400 as long, SecondaryMaterial: "Wood"}}), [[<minecraft:flint>, <minecraft:flint>, <minecraft:flint>],[null, <ore:stickWood>, null],[null, <ore:stickWood>, null]]);
recipes.addShaped(<gregtech:gt.metatool.01:4>.withTag({"GT.ToolStats": {PrimaryMaterial: "<minecraft:flint>", MaxDamage: 6400 as long, SecondaryMaterial: "Wood"}}), [[null, <minecraft:flint>, null],[null, <ore:stickWood>, null],[null, <ore:stickWood>, null]]);
recipes.addShaped(<gregtech:gt.metatool.01:6>.withTag({ench: [{lvl: 1 as short, id: 20 as short}], "GT.ToolStats": {PrimaryMaterial: "<minecraft:flint>", MaxDamage: 6400 as long, SecondaryMaterial: "Wood"}}), [[<minecraft:flint>, <minecraft:flint>, null],[<minecraft:flint>, <ore:stickWood>, null],[null, <ore:stickWood>, null]]);
recipes.addShaped(<gregtech:gt.metatool.01:8>.withTag({"GT.ToolStats": {PrimaryMaterial: "<minecraft:flint>", MaxDamage: 6400 as long, SecondaryMaterial: "Wood"}}), [[<minecraft:flint>, <minecraft:flint>, null],[null, <ore:stickWood>, null],[null, <ore:stickWood>, null]]);
mods.avaritia.ExtremeCrafting.addShaped(<gregtech:gt.metaitem.01:32752>, [[null, null, null, null, null, null, null, null, null],[null, null, null, null, null, null, null, null, null],[null, null, null, <ore:wireGt01SuperconductorMV>, <dreamcraft:item.IrradiantReinforcedAluminiumPlate>, <ore:wireGt01SuperconductorMV>, null, null, null],[null, null, null, <gregtech:gt.metaitem.03:32034>, <ore:platePolytetrafluoroethylene>, <gregtech:gt.metaitem.03:32034>, null, null, null],[null, null, null, <ore:circuitAdvanced>, <gregtech:gt.metaitem.01:32751>, <ore:circuitAdvanced>, null, null, null],[null, null, null, <gregtech:gt.metaitem.03:32034>, <ore:platePolytetrafluoroethylene>, <gregtech:gt.metaitem.03:32034>, null, null, null],[null, null, null, <ore:wireGt01SuperconductorMV>, <dreamcraft:item.IrradiantReinforcedAluminiumPlate>, <ore:wireGt01SuperconductorMV>, null, null, null],[null, null, null, null, null, null, null, null, null],[null, null, null, null, null, null, null, null, null]]);
mods.avaritia.ExtremeCrafting.addShaped(<gregtech:gt.metaitem.01:32753>, [[null, null, null, null, null, null, null, null, null],[null, null, null, null, <gregtech:gt.metaitem.03:32063>, null, null, null, null],[null, null, null, <ore:wireGt01SuperconductorHV>, <dreamcraft:item.IrradiantReinforcedTitaniumPlate>, <ore:wireGt01SuperconductorHV>, null, null, null],[null, null, null, <gregtech:gt.metaitem.03:32034>, <ore:plateEpoxid>, <gregtech:gt.metaitem.03:32034>, null, null, null],[null, null, null, <ore:circuitData>, <gregtech:gt.metaitem.01:32752>, <ore:circuitData>, null, null, null],[null, null, null, <gregtech:gt.metaitem.03:32034>, <ore:plateEpoxid>, <gregtech:gt.metaitem.03:32034>, null, null, null],[null, null, null, <ore:wireGt01SuperconductorHV>, <dreamcraft:item.IrradiantReinforcedTitaniumPlate>, <ore:wireGt01SuperconductorHV>, null, null, null],[null, null, null, null, <gregtech:gt.metaitem.03:32063>, null, null, null, null],[null, null, null, null, null, null, null, null, null]]);
mods.avaritia.ExtremeCrafting.addShaped(<gregtech:gt.metaitem.01:32754>, [[null, null, null, null, null, null, null, null, null],[null, null, null, null, <gregtech:gt.metaitem.03:32065>, null, null, null, null],[null, null, null, <ore:wireGt01SuperconductorEV>, <dreamcraft:item.IrradiantReinforcedTungstenPlate>, <ore:wireGt01SuperconductorEV>, null, null, null],[null, null, null, <gregtech:gt.metaitem.03:32034>, <ore:plateIndiumGalliumPhosphide>, <gregtech:gt.metaitem.03:32034>, null, null, null],[null, null, <ore:circuitElite>, <ore:circuitElite>, <gregtech:gt.metaitem.01:32753>, <ore:circuitElite>,  <ore:circuitElite>, null, null],[null, null, null, <gregtech:gt.metaitem.03:32034>, <ore:plateIndiumGalliumPhosphide>, <gregtech:gt.metaitem.03:32034>, null, null, null],[null, null, null, <ore:wireGt01SuperconductorEV>, <dreamcraft:item.IrradiantReinforcedTungstenPlate>, <ore:wireGt01SuperconductorEV>, null, null, null],[null, null, null, null, <gregtech:gt.metaitem.03:32065>, null, null, null, null],[null, null, null, null, null, null, null, null, null]]);
mods.avaritia.ExtremeCrafting.addShaped(<gregtech:gt.metaitem.01:32755>, [[null, null, null, null, null, null, null, null, null],[null, null, null, null, <gregtech:gt.metaitem.03:32051>, null, null, null, null],[null, null, <ore:wireGt01SuperconductorIV>, <ore:plateTripleSilicon>, <dreamcraft:item.IrradiantReinforcedTungstenSteelPlate>, <ore:plateTripleSilicon>, <ore:wireGt01SuperconductorIV>, null, null],[null, null, null, <gregtech:gt.metaitem.03:32035>, <ore:platePolybenzimidazole>, <gregtech:gt.metaitem.03:32035>, null, null, null],[null, <ore:wireGt01SuperconductorIV>, <ore:circuitMaster>, <ore:circuitMaster>, <gregtech:gt.metaitem.01:32754>, <ore:circuitMaster>, <ore:circuitMaster>, <ore:wireGt01SuperconductorIV>, null],[null, null, null, <gregtech:gt.metaitem.03:32035>, <ore:platePolybenzimidazole>, <gregtech:gt.metaitem.03:32035>, null, null, null],[null, null, <ore:wireGt01SuperconductorIV>, <ore:plateTripleSilicon>, <dreamcraft:item.IrradiantReinforcedTungstenSteelPlate>, <ore:plateTripleSilicon>, <ore:wireGt01SuperconductorIV>, null, null],[null, null, null, null, <gregtech:gt.metaitem.03:32051>, null, null, null, null],[null, null, null, null, null, null, null, null, null]]);
mods.avaritia.ExtremeCrafting.addShaped(<gregtech:gt.metaitem.01:32756>, [[null, null, null, null, null, null, null, null, null],[null, null, null, null, <gregtech:gt.metaitem.03:32053>, null, null, null, null],[null, null, <ore:wireGt01SuperconductorLuV>, <gregtech:gt.metaitem.03:32034>, <dreamcraft:item.IrradiantReinforcedChromePlate>, <gregtech:gt.metaitem.03:32034>, <ore:wireGt01SuperconductorLuV>, null, null],[null, null, <ore:plateQuadrupleSilicon>, <gregtech:gt.metaitem.03:32035>, <ore:plateDoublePolybenzimidazole>, <gregtech:gt.metaitem.03:32035>, <ore:plateQuadrupleSilicon>, null, null],[null, <ore:wireGt01SuperconductorLuV>, <ore:circuitUltimate>, <ore:circuitUltimate>, <gregtech:gt.metaitem.01:32755>, <ore:circuitUltimate>, <ore:circuitUltimate>, <ore:wireGt01SuperconductorLuV>, null],[null, null, <ore:plateQuadrupleSilicon>, <gregtech:gt.metaitem.03:32035>, <ore:plateDoublePolybenzimidazole>, <gregtech:gt.metaitem.03:32035>, <ore:plateQuadrupleSilicon>, null, null],[null, null, <ore:wireGt01SuperconductorLuV>, <gregtech:gt.metaitem.03:32034>, <dreamcraft:item.IrradiantReinforcedChromePlate>, <gregtech:gt.metaitem.03:32034>, <ore:wireGt01SuperconductorLuV>, null, null],[null, null, null, null, <gregtech:gt.metaitem.03:32053>, null, null, null, null],[null, null, null, null, null, null, null, null, null]]);
mods.avaritia.ExtremeCrafting.addShaped(<gregtech:gt.metaitem.01:32757>, [[null, null, null, null, <gregtech:gt.metaitem.03:32059>, null, null, null, null],[null, null, null, <ore:wireGt02SuperconductorZPM>, <ore:circuitInfinite>, <ore:wireGt02SuperconductorZPM>, null, null, null],[null, null, <ore:wireGt02SuperconductorZPM>, <gregtech:gt.metaitem.03:32035>, <AdvancedSolarPanel:asp_crafting_items:8>, <gregtech:gt.metaitem.03:32035>, <ore:wireGt02SuperconductorZPM>, null, null],[null, null, <ore:plateQuintupleSilicon>, <gregtech:gt.metaitem.03:32151>, <gregtech:gt.metaitem.01:32756>, <gregtech:gt.metaitem.03:32151>, <ore:plateQuintupleSilicon>, null, null],[null, <supersolarpanel:solarsplitter>, <ore:circuitInfinite>, <ore:circuitInfinite>, <ore:plateTriplePolybenzimidazole>, <ore:circuitInfinite>, <ore:circuitInfinite>, <supersolarpanel:solarsplitter>, null],[null, null, <ore:plateQuintupleSilicon>, <gregtech:gt.metaitem.03:32151>, <gregtech:gt.metaitem.01:32756>, <gregtech:gt.metaitem.03:32151>, <ore:plateQuintupleSilicon>, null, null],[null, null, <ore:wireGt02SuperconductorZPM>, <gregtech:gt.metaitem.03:32035>, <AdvancedSolarPanel:asp_crafting_items:8>, <gregtech:gt.metaitem.03:32035>, <ore:wireGt02SuperconductorZPM>, null, null],[null, null, null, <ore:wireGt02SuperconductorZPM>, <ore:circuitInfinite>, <ore:wireGt02SuperconductorZPM>, null, null, null],[null, null, null, null, <gregtech:gt.metaitem.03:32059>, null, null, null, null]]);
mods.avaritia.ExtremeCrafting.addShaped(<gregtech:gt.metaitem.01:32758>, [[null, null, null, <ore:wireGt04SuperconductorUV>, <gregtech:gt.metaitem.03:32048>, <ore:wireGt04SuperconductorUV>, null, null, null],[null, null, <gregtech:gt.metaitem.03:32161>, <ore:wireGt04SuperconductorUV>, <ore:circuitBio>, <ore:wireGt04SuperconductorUV>, <gregtech:gt.metaitem.03:32161>, null, null],[null, null, <ore:wireGt04SuperconductorUV>, <gregtech:gt.metaitem.03:32151>, <dreamcraft:item.IrradiantReinforcedNaquadriaPlate>, <gregtech:gt.metaitem.03:32151>, <ore:wireGt04SuperconductorUV>, null, null],[null, null, <IC2:itemPartCarbonPlate>, <gregtech:gt.metaitem.03:32153>, <gregtech:gt.metaitem.01:32757>, <gregtech:gt.metaitem.03:32153>, <IC2:itemPartCarbonPlate>, null, null],[<supersolarpanel:enderquantumcomponent>, <dreamcraft:item.IrradiantReinforcedNaquadriaPlate>, <ore:circuitBio>, <ore:circuitBio>, <ore:plateQuadruplePolybenzimidazole>, <ore:circuitBio>, <ore:circuitBio>, <dreamcraft:item.IrradiantReinforcedNaquadriaPlate>, <supersolarpanel:enderquantumcomponent>],[null, null, <IC2:itemPartCarbonPlate>, <gregtech:gt.metaitem.03:32153>, <gregtech:gt.metaitem.01:32757>, <gregtech:gt.metaitem.03:32153>, <IC2:itemPartCarbonPlate>, null, null],[null, null, <ore:wireGt04SuperconductorUV>, <gregtech:gt.metaitem.03:32151>, <dreamcraft:item.IrradiantReinforcedNaquadriaPlate>,<gregtech:gt.metaitem.03:32151>, <ore:wireGt04SuperconductorUV>, null, null],[null, null, <gregtech:gt.metaitem.03:32161>, <ore:wireGt04SuperconductorUV>, <ore:circuitBio>, <ore:wireGt04SuperconductorUV>, <gregtech:gt.metaitem.03:32161>, null, null],[null, null, null, <ore:wireGt04SuperconductorUV>, <gregtech:gt.metaitem.03:32048>, <ore:wireGt04SuperconductorUV>, null, null, null]]);
mods.avaritia.ExtremeCrafting.addShaped(<gregtech:gt.metaitem.01:32759>, [[null, null, <ore:wireGt08Superconductor>, <ore:plateDenseSilicon>, <gregtech:gt.metaitem.03:32068>, <ore:plateDenseSilicon>, <ore:wireGt08Superconductor>, null, null],[null, <gregtech:gt.metaitem.03:32163>, <ore:wireGt08Superconductor>, <gregtech:gt.metaitem.03:32153>, <ore:circuitNano>,<gregtech:gt.metaitem.03:32153>, <ore:wireGt08Superconductor>, <gregtech:gt.metaitem.03:32163>, null],[null, <ore:wireGt08Superconductor>, <dreamcraft:item.PicoWafer>, <ore:plateDenseSilicon>, <dreamcraft:item.IrradiantReinforcedNeutroniumPlate>, <ore:plateDenseSilicon>, <dreamcraft:item.PicoWafer>, <ore:wireGt08Superconductor>, null],[null, <ore:wireGt08Superconductor>, <IC2:itemPartCarbonPlate>, <ore:plateDenseSilicon>, <gregtech:gt.metaitem.01:32758>, <ore:plateDenseSilicon>, <IC2:itemPartCarbonPlate>, <ore:wireGt08Superconductor>, null],[<ore:wireGt08Superconductor>, <dreamcraft:item.IrradiantReinforcedNeutroniumPlate>, <ore:circuitNano>, <ore:circuitNano>, <ore:plateDensePolybenzimidazole>, <ore:circuitNano>, <ore:circuitNano>, <dreamcraft:item.IrradiantReinforcedNeutroniumPlate>, <ore:wireGt08Superconductor>],[null, <ore:wireGt08Superconductor>, <IC2:itemPartCarbonPlate>, <ore:plateDenseSilicon>, <gregtech:gt.metaitem.01:32758>, <ore:plateDenseSilicon>, <IC2:itemPartCarbonPlate>, <ore:wireGt08Superconductor>, null],[null, <ore:wireGt08Superconductor>, <dreamcraft:item.PicoWafer>, <ore:plateDenseSilicon>, <dreamcraft:item.IrradiantReinforcedNeutroniumPlate>, <ore:plateDenseSilicon>, <dreamcraft:item.PicoWafer>, <ore:wireGt08Superconductor>, null],[null, <gregtech:gt.metaitem.03:32163>, <ore:wireGt08Superconductor>, <gregtech:gt.metaitem.03:32153>, <ore:circuitNano>, <gregtech:gt.metaitem.03:32153>, <ore:wireGt08Superconductor>, <gregtech:gt.metaitem.03:32163>, null],[null, null, <ore:wireGt08Superconductor>, <ore:plateDenseSilicon>, <gregtech:gt.metaitem.03:32068>, <ore:plateDenseSilicon>, <ore:wireGt08Superconductor>, null, null]]);
mods.ic2.Canner.addBottleRecipe(<gregtech:gt.Thoriumcell>, <IC2:itemFuelRod>, <gregtech:gt.metaitem.01:2096> * 3);
mods.gregtech.Centrifuge.addRecipe([<gregtech:gt.metaitem.01:2802> * 8],  null, <minecraft:gravel> * 16, null, null, [10000], 50, 1920);
mods.gregtech.ChemicalReactor.addRecipe(<gregtech:gt.metaitem.01:2836> * 5, <liquid:steam> * 16000, <dreamcraft:item.PotassiumHydroxideDust> * 3, <gregtech:gt.integrated_circuit:1> * 0, <liquid:nitricacid> * 5000, 10, 30);
mods.tconstruct.Casting.addTableRecipe(<gregtech:gt.metaitem.01:32300>, <liquid:steel.molten> * 576, null, false, 100);
mods.tconstruct.Casting.addTableRecipe(<gregtech:gt.metaitem.01:32301>, <liquid:steel.molten> * 576, <dreamcraft:item.MoldFormPlate>, true, 100);
mods.tconstruct.Casting.addTableRecipe(<gregtech:gt.metaitem.01:32302>, <liquid:steel.molten> * 576, <dreamcraft:item.MoldFormCasing>, true, 100);
mods.tconstruct.Casting.addTableRecipe(<gregtech:gt.metaitem.01:32303>, <liquid:steel.molten> * 576, <dreamcraft:item.MoldFormGear>, true, 100);
mods.tconstruct.Casting.addTableRecipe(<gregtech:gt.metaitem.01:32304>, <liquid:steel.molten> * 576, <dreamcraft:item.MoldFormCoinage>, true, 100);
mods.tconstruct.Casting.addTableRecipe(<gregtech:gt.metaitem.01:32305>, <liquid:steel.molten> * 576, <dreamcraft:item.MoldFormBottle>, true, 100);
mods.tconstruct.Casting.addTableRecipe(<gregtech:gt.metaitem.01:32306>, <liquid:steel.molten> * 576,<dreamcraft:item.MoldFormIngot>, true, 100);
mods.tconstruct.Casting.addTableRecipe(<gregtech:gt.metaitem.01:32307>, <liquid:steel.molten> * 576, <dreamcraft:item.MoldFormBall>, true, 100);
mods.tconstruct.Casting.addTableRecipe(<gregtech:gt.metaitem.01:32308>, <liquid:steel.molten> * 576, <dreamcraft:item.MoldFormBlock>, true, 100);
mods.tconstruct.Casting.addTableRecipe(<gregtech:gt.metaitem.01:32309>, <liquid:steel.molten> * 576, <dreamcraft:item.MoldFormNuggets>, true, 100);
mods.tconstruct.Casting.addTableRecipe(<gregtech:gt.metaitem.01:32310>, <liquid:steel.molten> * 576, <dreamcraft:item.MoldFormBuns>, true, 100);
mods.tconstruct.Casting.addTableRecipe(<gregtech:gt.metaitem.01:32311>, <liquid:steel.molten> * 576, <dreamcraft:item.MoldFormBread>, true, 100);
mods.tconstruct.Casting.addTableRecipe(<gregtech:gt.metaitem.01:32312>, <liquid:steel.molten> * 576, <dreamcraft:item.MoldFormBaguette>, true, 100);
mods.tconstruct.Casting.addTableRecipe(<gregtech:gt.metaitem.01:32313>, <liquid:steel.molten> * 576, <dreamcraft:item.MoldFormCylinder>, true, 100);
mods.tconstruct.Casting.addTableRecipe(<gregtech:gt.metaitem.01:32314>, <liquid:steel.molten> * 576, <dreamcraft:item.MoldFormAnvil>, true, 100);
mods.tconstruct.Casting.addTableRecipe(<gregtech:gt.metaitem.01:32315>, <liquid:steel.molten> * 576, <dreamcraft:item.MoldFormName>, true, 100);
mods.tconstruct.Casting.addTableRecipe(<gregtech:gt.metaitem.01:32316>, <liquid:steel.molten> * 576, <dreamcraft:item.MoldFormArrowHead>, true, 100);
mods.tconstruct.Casting.addTableRecipe(<gregtech:gt.metaitem.01:32317>, <liquid:steel.molten> * 576, <dreamcraft:item.MoldFormSmallGear>, true, 100);
mods.tconstruct.Casting.addTableRecipe(<gregtech:gt.metaitem.01:32318>, <liquid:steel.molten> * 576, <dreamcraft:item.MoldFormStick>, true, 100);
mods.tconstruct.Casting.addTableRecipe(<gregtech:gt.metaitem.01:32319>, <liquid:steel.molten> * 576, <dreamcraft:item.MoldFormBolt>, true, 100);
mods.tconstruct.Casting.addTableRecipe(<gregtech:gt.metaitem.01:32320>, <liquid:steel.molten> * 576, <dreamcraft:item.MoldFormRound>, true, 100);
mods.tconstruct.Casting.addTableRecipe(<gregtech:gt.metaitem.01:32321>, <liquid:steel.molten> * 576, <dreamcraft:item.MoldFormScrew>, true, 100);
mods.tconstruct.Casting.addTableRecipe(<gregtech:gt.metaitem.01:32322>, <liquid:steel.molten> * 576, <dreamcraft:item.MoldFormRing>, true, 100);
mods.tconstruct.Casting.addTableRecipe(<gregtech:gt.metaitem.01:32323>, <liquid:steel.molten> * 576, <dreamcraft:item.MoldFormStickLong>, true, 100);
mods.tconstruct.Casting.addTableRecipe(<gregtech:gt.metaitem.01:32325>, <liquid:steel.molten> * 576, <dreamcraft:item.MoldFormTurbineBlade>, true, 100);
mods.tconstruct.Casting.addTableRecipe(<gregtech:gt.metaitem.01:32324>, <liquid:steel.molten> * 576, <dreamcraft:item.MoldFormRotor>, true, 100);
mods.tconstruct.Casting.addTableRecipe(<gregtech:gt.metaitem.01:32350>, <liquid:steel.molten> * 576, <dreamcraft:item.ShapePlate>, true, 100);
mods.tconstruct.Casting.addTableRecipe(<gregtech:gt.metaitem.01:32351>, <liquid:steel.molten> * 576, <dreamcraft:item.ShapeRod>, true, 100);
mods.tconstruct.Casting.addTableRecipe(<gregtech:gt.metaitem.01:32352>, <liquid:steel.molten> * 576, <dreamcraft:item.ShapeBolt>, true, 100);
mods.tconstruct.Casting.addTableRecipe(<gregtech:gt.metaitem.01:32354>, <liquid:steel.molten> * 576, <dreamcraft:item.ShapeCell>, true, 100);
mods.tconstruct.Casting.addTableRecipe(<gregtech:gt.metaitem.01:32353>, <liquid:steel.molten> * 576, <dreamcraft:item.ShapeRing>, true, 100);
mods.tconstruct.Casting.addTableRecipe(<gregtech:gt.metaitem.01:32355>, <liquid:steel.molten> * 576, <dreamcraft:item.ShapeIngot>, true, 100);
mods.tconstruct.Casting.addTableRecipe(<gregtech:gt.metaitem.01:32356>, <liquid:steel.molten> * 576, <dreamcraft:item.ShapeWire>, true, 100);
mods.tconstruct.Casting.addTableRecipe(<gregtech:gt.metaitem.01:32357>, <liquid:steel.molten> * 576, <dreamcraft:item.ShapeCasing>, true, 100);
mods.tconstruct.Casting.addTableRecipe(<gregtech:gt.metaitem.01:32358>, <liquid:steel.molten> * 576, <dreamcraft:item.ShapeTinyPipe>, true, 100);
mods.tconstruct.Casting.addTableRecipe(<gregtech:gt.metaitem.01:32359>, <liquid:steel.molten> * 576, <dreamcraft:item.ShapeSmallPipe>, true, 100);
mods.tconstruct.Casting.addTableRecipe(<gregtech:gt.metaitem.01:32360>, <liquid:steel.molten> * 576, <dreamcraft:item.ShapeNormalPipe>, true, 100);
mods.tconstruct.Casting.addTableRecipe(<gregtech:gt.metaitem.01:32361>, <liquid:steel.molten> * 576, <dreamcraft:item.ShapeLargePipe>, true, 100);
mods.tconstruct.Casting.addTableRecipe(<gregtech:gt.metaitem.01:32362>, <liquid:steel.molten> * 576, <dreamcraft:item.ShapeHugePipe>, true, 100);
mods.tconstruct.Casting.addTableRecipe(<gregtech:gt.metaitem.01:32363>, <liquid:steel.molten> * 576, <dreamcraft:item.ShapeBlock>, true, 100);
mods.tconstruct.Casting.addTableRecipe(<gregtech:gt.metaitem.01:32364>, <liquid:steel.molten> * 576, <dreamcraft:item.ShapeSwordBlade>, true, 100);
mods.tconstruct.Casting.addTableRecipe(<gregtech:gt.metaitem.01:32365>, <liquid:steel.molten> * 576, <dreamcraft:item.ShapePickaxeHead>, true, 100);
mods.tconstruct.Casting.addTableRecipe(<gregtech:gt.metaitem.01:32366>, <liquid:steel.molten> * 576, <dreamcraft:item.ShapeShovelHead>, true, 100);
mods.tconstruct.Casting.addTableRecipe(<gregtech:gt.metaitem.01:32367>, <liquid:steel.molten> * 576, <dreamcraft:item.ShapeAxeHead>, true, 100);
mods.tconstruct.Casting.addTableRecipe(<gregtech:gt.metaitem.01:32368>, <liquid:steel.molten> * 576, <dreamcraft:item.ShapeHoeHead>, true, 100);
mods.tconstruct.Casting.addTableRecipe(<gregtech:gt.metaitem.01:32369>, <liquid:steel.molten> * 576, <dreamcraft:item.ShapeHammerHead>, true, 100);
mods.tconstruct.Casting.addTableRecipe(<gregtech:gt.metaitem.01:32370>, <liquid:steel.molten> * 576, <dreamcraft:item.ShapeFileHead>, true, 100);
mods.tconstruct.Casting.addTableRecipe(<gregtech:gt.metaitem.01:32371>, <liquid:steel.molten> * 576, <dreamcraft:item.ShapeSawBlade>, true, 100);
mods.tconstruct.Casting.addTableRecipe(<gregtech:gt.metaitem.01:32372>, <liquid:steel.molten> * 576, <dreamcraft:item.ShapeGear>, true, 100);
mods.tconstruct.Casting.addTableRecipe(<gregtech:gt.metaitem.01:32373>, <liquid:steel.molten> * 576, <dreamcraft:item.ShapeBottle>, true, 100);
mods.tconstruct.Casting.addTableRecipe(<gregtech:gt.metaitem.01:32374>, <liquid:steel.molten> * 576, <dreamcraft:item.ShapeRotor>, true, 100);
mods.tconstruct.Casting.addTableRecipe(<gregtech:gt.metaitem.01:32376>, <liquid:steel.molten> * 576, <dreamcraft:item.ShapeTurbineBlade>, true, 100);
mods.tconstruct.Casting.addTableRecipe(<gregtech:gt.metaitem.01:32375>, <liquid:steel.molten> * 576, <dreamcraft:item.ShapeSmallGear>, true, 100);
<IC2:itemPartCircuit>.addTooltip(format.red("LV-tier"));
<gregtech:gt.metaitem.01:32701>.addTooltip(format.gold("LV-tier"));
<gregtech:gt.metaitem.03:32078>.addTooltip(format.yellow("LV-tier"));
<gregtech:gt.metaitem.01:32702>.addTooltip(format.red("MV-tier"));
<gregtech:gt.metaitem.03:32079>.addTooltip(format.gold("MV-tier"));
<gregtech:gt.metaitem.03:32080>.addTooltip(format.yellow("MV-tier"));
<IC2:itemPartCircuitAdv>.addTooltip(format.gold("HV-tier"));
<gregtech:gt.metaitem.01:32703>.addTooltip(format.yellow("HV-tier"));
<gregtech:gt.metaitem.03:32082>.addTooltip(format.green("HV-tier"));
<gregtech:gt.metaitem.01:32704>.addTooltip(format.yellow("EV-tier"));
<gregtech:gt.metaitem.03:32083>.addTooltip(format.green("EV-tier"));
<gregtech:gt.metaitem.03:32085>.addTooltip(format.aqua("EV-tier"));
<gregtech:gt.metaitem.01:32705>.addTooltip(format.yellow("IV-tier"));
<gregtech:gt.metaitem.03:32084>.addTooltip(format.green("IV-tier"));
<gregtech:gt.metaitem.03:32086>.addTooltip(format.aqua("IV-tier"));
<gregtech:gt.metaitem.03:32089>.addTooltip(format.blue("IV-tier"));
<gregtech:gt.metaitem.01:32706>.addTooltip(format.green("LuV-tier"));
<gregtech:gt.metaitem.03:32087>.addTooltip(format.aqua("LuV-tier"));
<gregtech:gt.metaitem.03:32096>.addTooltip(format.blue("LuV-tier"));
<gregtech:gt.metaitem.03:32092>.addTooltip(format.darkPurple("LuV-tier"));
<gregtech:gt.metaitem.03:32088>.addTooltip(format.aqua("ZPM-tier"));
<gregtech:gt.metaitem.03:32090>.addTooltip(format.blue("ZPM-tier"));
<gregtech:gt.metaitem.03:32093>.addTooltip(format.darkPurple("ZPM-tier"));
<gregtech:gt.metaitem.03:32097>.addTooltip(format.green("ZPM-tier"));
<gregtech:gt.metaitem.03:32091>.addTooltip(format.blue("UV-tier"));
<gregtech:gt.metaitem.03:32094>.addTooltip(format.darkPurple("UV-tier"));
<gregtech:gt.metaitem.03:32098>.addTooltip(format.aqua("UV-tier"));
<gregtech:gt.metaitem.03:32095>.addTooltip(format.darkPurple("UHV-tier"));
<gregtech:gt.metaitem.03:32099>.addTooltip(format.green("UHV-tier"));
<gregtech:gt.metaitem.03:32120>.addTooltip(format.green("UEV-tier"));
<gregtech:gt.metaitem.01:32510>.addTooltip(format.red("LV-tier"));
<gregtech:gt.metaitem.01:32511>.addTooltip(format.gold("LV-tier"));
<gregtech:gt.metaitem.01:32517>.addTooltip(format.yellow("LV-tier"));
<gregtech:gt.metaitem.01:32518>.addTooltip(format.darkRed("LV-tier"));
<gregtech:gt.metaitem.01:32519>.addTooltip(format.green("LV-tier"));
<gregtech:gt.metaitem.01:32520>.addTooltip(format.red("MV-tier"));
<gregtech:gt.metaitem.01:32521>.addTooltip(format.gold("MV-tier"));
<gregtech:gt.metaitem.01:32527>.addTooltip(format.yellow("MV-tier"));
<gregtech:gt.metaitem.01:32528>.addTooltip(format.darkRed("MV-tier"));
<gregtech:gt.metaitem.01:32529>.addTooltip(format.green("MV-tier"));
<gregtech:gt.metaitem.01:32530>.addTooltip(format.red("HV-tier"));
<gregtech:gt.metaitem.01:32531>.addTooltip(format.gold("HV-tier"));
<gregtech:gt.metaitem.01:32537>.addTooltip(format.yellow("HV-tier"));
<gregtech:gt.metaitem.01:32538>.addTooltip(format.darkRed("HV-tier"));
<gregtech:gt.metaitem.01:32539>.addTooltip(format.green("HV-tier"));
<IC2:itemBatCrystal:*>.addTooltip(format.darkBlue("HV-tier"));
<gregtech:gt.metaitem.01:32540>.addTooltip(format.green("EV-tier"));
<IC2:itemBatLamaCrystal:*>.addTooltip(format.darkBlue("EV-tier"));
<gregtech:gt.metaitem.01:32545>.addTooltip(format.green("IV-tier"));
<gregtech:gt.metaitem.01:32597>.addTooltip(format.gold("IV-tier"));
<gregtech:gt.metaitem.01:32550>.addTooltip(format.green("LuV-tier"));
<gregtech:gt.metaitem.01:32599>.addTooltip(format.gold("LuV-tier"));
<gregtech:gt.metaitem.01:32555>.addTooltip(format.green("ZPM-tier"));
<gregtech:gt.metaitem.01:32736>.addTooltip(format.gold("ZPM-tier"));
<gregtech:gt.metaitem.01:32598>.addTooltip(format.red("ZPM-tier"));
<gregtech:gt.metaitem.01:32560>.addTooltip(format.green("UV-tier"));
<gregtech:gt.metaitem.01:32737>.addTooltip(format.gold("UV-tier"));
<gregtech:gt.metaitem.01:32605>.addTooltip(format.red("UV-tier"));
<gregtech:gt.metaitem.01:32570>.addTooltip(format.green("UHV-tier"));
<gregtech:gt.metaitem.01:32575>.addTooltip(format.green("UEV-tier"));
<gregtech:gt.metaitem.01:32580>.addTooltip(format.green("UIV-tier"));
<gregtech:gt.metaitem.01:32585>.addTooltip(format.green("UMV-tier"));
<gregtech:gt.metaitem.01:32609>.addTooltip(format.gold("UMV-tier"));
<gregtech:gt.metaitem.01:32590>.addTooltip(format.green("UXV-tier"));
<gregtech:gt.blockmachines:1156>.addTooltip("Work Area 16 Blocks Radius = 4 Chunks");
<gregtech:gt.blockmachines:2100>.addTooltip("Work Area 32 Blocks Radius = 16 Chunks");
<gregtech:gt.blockmachines:2101>.addTooltip("Work Area 48 Blocks Radius = 36 Chunks");
<gregtech:gt.blockmachines:1173>.addTooltip("Work Area 128 Blocks Radius = 256 Chunks");
comb.add(<gregtech:gt.comb>);
oreDict.combLv.add(<gregtech:gt.comb>);
comb.add(<gregtech:gt.comb:1>);
oreDict.combLv.add(<gregtech:gt.comb:1>);
comb.add(<gregtech:gt.comb:2>);
oreDict.combLv.add(<gregtech:gt.comb:2>);
comb.add(<gregtech:gt.comb:3>);
oreDict.combLv.add(<gregtech:gt.comb:3>);
comb.add(<gregtech:gt.comb:4>);
oreDict.combLv.add(<gregtech:gt.comb:4>);
comb.add(<gregtech:gt.comb:5>);
oreDict.combLv.add(<gregtech:gt.comb:5>);
comb.add(<gregtech:gt.comb:6>);
oreDict.combHv.add(<gregtech:gt.comb:6>);
comb.add(<gregtech:gt.comb:7>);
oreDict.combHv.add(<gregtech:gt.comb:7>);
comb.add(<gregtech:gt.comb:8>);
oreDict.combHv.add(<gregtech:gt.comb:8>);
comb.add(<gregtech:gt.comb:9>);
oreDict.combHv.add(<gregtech:gt.comb:9>);
comb.add(<gregtech:gt.comb:10>);
oreDict.combHv.add(<gregtech:gt.comb:10>);
comb.add(<gregtech:gt.comb:11>);
oreDict.combLv.add(<gregtech:gt.comb:11>);
comb.add(<gregtech:gt.comb:12>);
oreDict.combLv.add(<gregtech:gt.comb:12>);
comb.add(<gregtech:gt.comb:13>);
oreDict.combMv.add(<gregtech:gt.comb:13>);
comb.add(<gregtech:gt.comb:14>);
oreDict.combHv.add(<gregtech:gt.comb:14>);
comb.add(<gregtech:gt.comb:15>);
oreDict.combHv.add(<gregtech:gt.comb:15>);
comb.add(<gregtech:gt.comb:16>);
oreDict.combLv.add(<gregtech:gt.comb:16>);
comb.add(<gregtech:gt.comb:17>);
oreDict.combMv.add(<gregtech:gt.comb:17>);
comb.add(<gregtech:gt.comb:18>);
oreDict.combHv.add(<gregtech:gt.comb:18>);
comb.add(<gregtech:gt.comb:19>);
oreDict.combHv.add(<gregtech:gt.comb:19>);
comb.add(<gregtech:gt.comb:20>);
oreDict.combHv.add(<gregtech:gt.comb:20>);
comb.add(<gregtech:gt.comb:21>);
oreDict.combMv.add(<gregtech:gt.comb:21>);
comb.add(<gregtech:gt.comb:22>);
oreDict.combLv.add(<gregtech:gt.comb:22>);
comb.add(<gregtech:gt.comb:23>);
oreDict.combLv.add(<gregtech:gt.comb:23>);
comb.add(<gregtech:gt.comb:24>);
oreDict.combLv.add(<gregtech:gt.comb:24>);
comb.add(<gregtech:gt.comb:25>);
oreDict.combMv.add(<gregtech:gt.comb:25>);
comb.add(<gregtech:gt.comb:26>);
oreDict.combLv.add(<gregtech:gt.comb:26>);
comb.add(<gregtech:gt.comb:27>);
oreDict.combHv.add(<gregtech:gt.comb:27>);
comb.add(<gregtech:gt.comb:28>);
oreDict.combHv.add(<gregtech:gt.comb:28>);
comb.add(<gregtech:gt.comb:29>);
oreDict.combHv.add(<gregtech:gt.comb:29>);
comb.add(<gregtech:gt.comb:30>);
oreDict.combHv.add(<gregtech:gt.comb:30>);
comb.add(<gregtech:gt.comb:31>);
oreDict.combHv.add(<gregtech:gt.comb:31>);
comb.add(<gregtech:gt.comb:32>);
oreDict.combEv.add(<gregtech:gt.comb:32>);
comb.add(<gregtech:gt.comb:33>);
oreDict.combLv.add(<gregtech:gt.comb:33>);
comb.add(<gregtech:gt.comb:34>);
oreDict.combLv.add(<gregtech:gt.comb:34>);
comb.add(<gregtech:gt.comb:35>);
oreDict.combLv.add(<gregtech:gt.comb:35>);
comb.add(<gregtech:gt.comb:36>);
oreDict.combLv.add(<gregtech:gt.comb:36>);
comb.add(<gregtech:gt.comb:37>);
oreDict.combLv.add(<gregtech:gt.comb:37>);
comb.add(<gregtech:gt.comb:38>);
oreDict.combLv.add(<gregtech:gt.comb:38>);
comb.add(<gregtech:gt.comb:39>);
oreDict.combLv.add(<gregtech:gt.comb:39>);
comb.add(<gregtech:gt.comb:40>);
oreDict.combLv.add(<gregtech:gt.comb:40>);
comb.add(<gregtech:gt.comb:41>);
oreDict.combLv.add(<gregtech:gt.comb:41>);
comb.add(<gregtech:gt.comb:42>);
oreDict.combLv.add(<gregtech:gt.comb:42>);
comb.add(<gregtech:gt.comb:43>);
oreDict.combLv.add(<gregtech:gt.comb:43>);
comb.add(<gregtech:gt.comb:44>);
oreDict.combLv.add(<gregtech:gt.comb:44>);
comb.add(<gregtech:gt.comb:45>);
oreDict.combLv.add(<gregtech:gt.comb:45>);
comb.add(<gregtech:gt.comb:46>);
oreDict.combLv.add(<gregtech:gt.comb:46>);
comb.add(<gregtech:gt.comb:47>);
oreDict.combLv.add(<gregtech:gt.comb:47>);
comb.add(<gregtech:gt.comb:48>);
oreDict.combLv.add(<gregtech:gt.comb:48>);
comb.add(<gregtech:gt.comb:49>);
oreDict.combLv.add(<gregtech:gt.comb:49>);
comb.add(<gregtech:gt.comb:50>);
oreDict.combLv.add(<gregtech:gt.comb:50>);
comb.add(<gregtech:gt.comb:51>);
oreDict.combLv.add(<gregtech:gt.comb:51>);
comb.add(<gregtech:gt.comb:52>);
oreDict.combLv.add(<gregtech:gt.comb:52>);
comb.add(<gregtech:gt.comb:53>);
oreDict.combLv.add(<gregtech:gt.comb:53>);
comb.add(<gregtech:gt.comb:54>);
oreDict.combLv.add(<gregtech:gt.comb:54>);
comb.add(<gregtech:gt.comb:55>);
oreDict.combLv.add(<gregtech:gt.comb:55>);
comb.add(<gregtech:gt.comb:56>);
oreDict.combLv.add(<gregtech:gt.comb:56>);
comb.add(<gregtech:gt.comb:57>);
oreDict.combLv.add(<gregtech:gt.comb:57>);
comb.add(<gregtech:gt.comb:58>);
oreDict.combLv.add(<gregtech:gt.comb:58>);
comb.add(<gregtech:gt.comb:59>);
oreDict.combLv.add(<gregtech:gt.comb:59>);
comb.add(<gregtech:gt.comb:60>);
oreDict.combLv.add(<gregtech:gt.comb:60>);
comb.add(<gregtech:gt.comb:61>);
oreDict.combLv.add(<gregtech:gt.comb:61>);
comb.add(<gregtech:gt.comb:62>);
oreDict.combLv.add(<gregtech:gt.comb:62>);
comb.add(<gregtech:gt.comb:63>);
oreDict.combLv.add(<gregtech:gt.comb:63>);
comb.add(<gregtech:gt.comb:64>);
oreDict.combLv.add(<gregtech:gt.comb:64>);
comb.add(<gregtech:gt.comb:65>);
oreDict.combLv.add(<gregtech:gt.comb:65>);
comb.add(<gregtech:gt.comb:66>);
oreDict.combIv.add(<gregtech:gt.comb:66>);
comb.add(<gregtech:gt.comb:67>);
oreDict.combHv.add(<gregtech:gt.comb:67>);
comb.add(<gregtech:gt.comb:68>);
oreDict.combIv.add(<gregtech:gt.comb:68>);
comb.add(<gregtech:gt.comb:69>);
oreDict.combHv.add(<gregtech:gt.comb:69>);
comb.add(<gregtech:gt.comb:70>);
oreDict.combIv.add(<gregtech:gt.comb:70>);
comb.add(<gregtech:gt.comb:71>);
oreDict.combLv.add(<gregtech:gt.comb:71>);
comb.add(<gregtech:gt.comb:72>);
oreDict.combIv.add(<gregtech:gt.comb:72>);
comb.add(<gregtech:gt.comb:73>);
oreDict.combMv.add(<gregtech:gt.comb:73>);
comb.add(<gregtech:gt.comb:74>);
oreDict.combMv.add(<gregtech:gt.comb:74>);
comb.add(<gregtech:gt.comb:75>);
oreDict.combHv.add(<gregtech:gt.comb:75>);
comb.add(<gregtech:gt.comb:76>);
oreDict.combLv.add(<gregtech:gt.comb:76>);
comb.add(<gregtech:gt.comb:77>);
oreDict.combIv.add(<gregtech:gt.comb:77>);
comb.add(<gregtech:gt.comb:78>);
oreDict.combIv.add(<gregtech:gt.comb:78>);
comb.add(<gregtech:gt.comb:79>);
oreDict.combIv.add(<gregtech:gt.comb:79>);
comb.add(<gregtech:gt.comb:80>);
oreDict.combIv.add(<gregtech:gt.comb:80>);
comb.add(<gregtech:gt.comb:81>);
oreDict.combLv.add(<gregtech:gt.comb:81>);
comb.add(<gregtech:gt.comb:82>);
oreDict.combEv.add(<gregtech:gt.comb:82>);
comb.add(<gregtech:gt.comb:83>);
oreDict.combIv.add(<gregtech:gt.comb:83>);
comb.add(<gregtech:gt.comb:84>);
oreDict.combLuv.add(<gregtech:gt.comb:84>);
comb.add(<gregtech:gt.comb:85>);
oreDict.combZPM.add(<gregtech:gt.comb:85>);
comb.add(<gregtech:gt.comb:86>);
oreDict.combMv.add(<gregtech:gt.comb:86>);
comb.add(<gregtech:gt.comb:87>);
oreDict.combHv.add(<gregtech:gt.comb:87>);
comb.add(<gregtech:gt.comb:88>);
oreDict.combHv.add(<gregtech:gt.comb:88>);
comb.add(<gregtech:gt.comb:89>);
oreDict.combEv.add(<gregtech:gt.comb:89>);
comb.add(<gregtech:gt.comb:90>);
oreDict.combEv.add(<gregtech:gt.comb:90>);
comb.add(<gregtech:gt.comb:91>);
oreDict.combHv.add(<gregtech:gt.comb:91>);
comb.add(<gregtech:gt.comb:92>);
oreDict.combEv.add(<gregtech:gt.comb:92>);
comb.add(<gregtech:gt.comb:93>);
oreDict.combIv.add(<gregtech:gt.comb:93>);
comb.add(<gregtech:gt.comb:94>);
oreDict.combIv.add(<gregtech:gt.comb:94>);
comb.add(<gregtech:gt.comb:95>);
oreDict.combIv.add(<gregtech:gt.comb:95>);
comb.add(<gregtech:gt.comb:96>);
oreDict.combIv.add(<gregtech:gt.comb:96>);
comb.add(<gregtech:gt.comb:97>);
oreDict.combIv.add(<gregtech:gt.comb:97>);
comb.add(<gregtech:gt.comb:98>);
oreDict.combIv.add(<gregtech:gt.comb:98>);
comb.add(<gregtech:gt.comb:99>);
oreDict.combLuv.add(<gregtech:gt.comb:99>);
comb.add(<gregtech:gt.comb:100>);
oreDict.combLuv.add(<gregtech:gt.comb:100>);
comb.add(<gregtech:gt.comb:101>);
oreDict.combZPM.add(<gregtech:gt.comb:101>);
comb.add(<gregtech:gt.comb:102>);
oreDict.combEv.add(<gregtech:gt.comb:102>);
comb.add(<gregtech:gt.comb:103>);
oreDict.combEv.add(<gregtech:gt.comb:103>);
comb.add(<gregtech:gt.comb:104>);
oreDict.combMv.add(<gregtech:gt.comb:104>);
comb.add(<gregtech:gt.comb:105>);
oreDict.combMv.add(<gregtech:gt.comb:105>);
comb.add(<gregtech:gt.comb:106>);
oreDict.combMv.add(<gregtech:gt.comb:106>);
comb.add(<gregtech:gt.comb:107>);
oreDict.combIv.add(<gregtech:gt.comb:107>);
comb.add(<gregtech:gt.comb:108>);
oreDict.combIv.add(<gregtech:gt.comb:108>);
comb.add(<gregtech:gt.comb:109>);
oreDict.combIv.add(<gregtech:gt.comb:109>);
comb.add(<gregtech:gt.comb:110>);
oreDict.combLuv.add(<gregtech:gt.comb:110>);
comb.add(<gregtech:gt.comb:111>);
oreDict.combLuv.add(<gregtech:gt.comb:111>);
comb.add(<gregtech:gt.comb:112>);
oreDict.combLuv.add(<gregtech:gt.comb:112>);
comb.add(<gregtech:gt.comb:113>);
oreDict.combZPM.add(<gregtech:gt.comb:113>);
comb.add(<gregtech:gt.comb:114>);
oreDict.combZPM.add(<gregtech:gt.comb:114>);
comb.add(<gregtech:gt.comb:115>);
oreDict.combZPM.add(<gregtech:gt.comb:115>);
comb.add(<gregtech:gt.comb:116>);
oreDict.combZPM.add(<gregtech:gt.comb:116>);
comb.add(<gregtech:gt.comb:117>);
oreDict.combUv.add(<gregtech:gt.comb:117>);
comb.add(<gregtech:gt.comb:118>);
oreDict.combUhv.add(<gregtech:gt.comb:118>);
comb.add(<gregtech:gt.comb:119>);
oreDict.combUev.add(<gregtech:gt.comb:119>);
