recipes.addShaped(<openmodularturrets:baseTierTwoBlock>, [[<ore:plateDarkSteel>, <EnderIO:blockCapBank:1>.withTag({type: "SIMPLE", storedEnergyRF: 0}), <ore:plateDarkSteel>],[<openmodularturrets:ioBus>, <openmodularturrets:sensorTierThreeItem>, <openmodularturrets:ioBus>],[<ore:plateDarkSteel>, <EnderIO:itemBasicCapacitor>, <ore:plateDarkSteel>]]);
recipes.addShaped(<openmodularturrets:baseTierThreeBlock>, [[<ore:plateEnergeticAlloy>, <EnderIO:blockCapBank:2>.withTag({type: "ACTIVATED", storedEnergyRF: 0}), <ore:plateEnergeticAlloy>],[<openmodularturrets:ioBus>, <openmodularturrets:sensorTierFourItem>, <openmodularturrets:ioBus>],[<ore:plateEnergeticAlloy>, <EnderIO:itemBasicCapacitor:1>, <ore:plateEnergeticAlloy>]]);
recipes.addShaped(<openmodularturrets:baseTierFourBlock>, [[<ore:plateVibrantAlloy>, <EnderIO:blockCapBank:3>.withTag({type: "VIBRANT", storedEnergyRF: 0}), <ore:plateVibrantAlloy>],[<openmodularturrets:ioBus>, <openmodularturrets:sensorTierFiveItem>, <openmodularturrets:ioBus>],[<ore:plateVibrantAlloy>, <EnderIO:itemBasicCapacitor:2>, <ore:plateVibrantAlloy>]]);
mods.gregtech.ChemicalBath.addRecipe([<openmodularturrets:hardWallTierOne>], <gregtech:gt.blockmachines:4985>, <liquid:wet.concrete> * 144, [10000], 200, 16);
mods.gregtech.ChemicalBath.addRecipe([<openmodularturrets:hardWallTierTwo>], <gregtech:gt.blockmachines:4461>, <liquid:wet.concrete> * 144, [10000], 200, 30);
mods.gregtech.ChemicalBath.addRecipe([<openmodularturrets:hardWallTierThree>], <gregtech:gt.blockmachines:4460>, <liquid:wet.concrete> * 144, [10000], 200, 64);
mods.gregtech.ChemicalBath.addRecipe([<openmodularturrets:hardWallTierFour>], <gregtech:gt.blockmachines:4462>, <liquid:wet.concrete> * 144, [10000], 200, 120);
mods.gregtech.ChemicalBath.addRecipe([<openmodularturrets:hardWallTierFive>], <gregtech:gt.blockmachines:4463>, <liquid:wet.concrete> * 144, [10000], 200, 256);
mods.gregtech.Mixer.addRecipe(<openmodularturrets:blazingClayCraftable> * 32, [<gregtech:gt.metaitem.01:2805> * 4, <minecraft:redstone> * 4, <minecraft:blaze_powder>], 200, 30);
