mods.gregtech.CuttingSaw.addRecipe([<Ztones:lampf> * 4], <ProjRed|Illumination:projectred.illumination.lamp:16>, <liquid:water> * 100, 200, 4);
mods.gregtech.CuttingSaw.addRecipe([<Ztones:lampf> * 4], <ProjRed|Illumination:projectred.illumination.lamp:16>, <liquid:ic2distilledwater> * 75, 200, 4);
mods.gregtech.CuttingSaw.addRecipe([<Ztones:lampf> * 4], <ProjRed|Illumination:projectred.illumination.lamp:16>, <liquid:lubricant> * 25, 100, 4);
mods.gregtech.CuttingSaw.addRecipe([<Ztones:lampt> * 4], <ProjRed|Illumination:projectred.illumination.lamp:24>, <liquid:water> * 100, 200, 4);
mods.gregtech.CuttingSaw.addRecipe([<Ztones:lampt> * 4], <ProjRed|Illumination:projectred.illumination.lamp:24>, <liquid:ic2distilledwater> * 75, 200, 4);
mods.gregtech.CuttingSaw.addRecipe([<Ztones:lampt> * 4], <ProjRed|Illumination:projectred.illumination.lamp:24>, <liquid:lubricant> * 25, 100, 4);
mods.gregtech.CuttingSaw.addRecipe([<Ztones:lampb> * 4], <ProjRed|Illumination:projectred.illumination.lamp:23>, <liquid:water> * 100, 200, 4);
mods.gregtech.CuttingSaw.addRecipe([<Ztones:lampb> * 4], <ProjRed|Illumination:projectred.illumination.lamp:23>, <liquid:ic2distilledwater> * 75, 200, 4);
mods.gregtech.CuttingSaw.addRecipe([<Ztones:lampb> * 4], <ProjRed|Illumination:projectred.illumination.lamp:23>, <liquid:lubricant> * 25, 100, 4);
